### ISSUE TITLE
Unable to get the outputs as shown

### ISSUE THREAD

**Issue by Mukulareddy** [bhadreshpsavani/CarPartsDetectionChallenge#5]
/content/CarPartsDetectionChallenge/Data/Model_Weights/trained_weights_final.h5 model, anchors, and classes loaded in 15.33sec.
W0624 18:42:00.195236 139658591704960 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Found 5 input labels: ['Light', 'Glass', 'SideGlass', 'Door', 'Wheel'] ...
Found 10 input images: ['00231.jpg', '00228.jpg', '00227.jpg', '00230.jpg', '00225.jpg'] ...
/content/CarPartsDetectionChallenge/Data/Source_Images/Test_Images/00231.jpg
(416, 416, 3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: Attempting to use uninitialized value batch_normalization_105/gamma
	 [[{{node batch_normalization_105/gamma/read}}]]
	 [[concat_11/_85]]
  (1) Failed precondition: Attempting to use uninitialized value batch_normalization_105/gamma
	 [[{{node batch_normalization_105/gamma/read}}]]
0 successful operations.
0 derived errors ignored.

**Comment by bhadreshpsavani** [comment]
This issue comes when you were testing model output, isn't it?

**Comment by Mukulareddy** [comment]
Yes. I am getting this issue when I'm testing the model.

Thanks & Regards
S Mukula

**Comment by bhadreshpsavani** [comment]
Hi Mukula,

I reproduced the issue but could not resolve it today.

I used [this ](https://github.com/AntonMu/TrainYourOwnYOLO) for creating this project, you can also follow the same for now, its well-maintained repository.

I might not get enough time to work on this issue right now, I will fix it later

**Comment by Mukulareddy** [comment]
Hi Bhadresh
That's okay. I understand you might be busy.
I would like to know if the custom model you trained for carpart detection
is trained_weights_final.h5.


Thanks and regards
S.Mukula

**Comment by bhadreshpsavani** [comment]
Hi Mukula,

Its `trained_weights_final.h5`.

Thanks,
Bhadresh

**Comment by Mukulareddy** [comment]
Ok thank you so much.

Thanks & Regards
S Mukula

**Comment by Mukulareddy** [comment]
Thanks. I followed the link which you sent.it worked for me.

Thanks & Regards
S Mukula

**Comment by bhadreshpsavani** [comment]
Hi @Mukulareddy 
I have fixed the issue
