### ISSUE TITLE
ImportError: No module named keras_yolo3.yolo

### ISSUE THREAD

**Issue by vincentcheng62** [bhadreshpsavani/CarPartsDetectionChallenge#7]
I got the following error when I try to run  "python3 Minimal_Example.py"

========================================================
Detecting Cat Faces by calling: 

 python /home/hmcheng/Downloads/CarPartsDetectionChallenge-master/3_Inference/Detector.py --input_path /home/hmcheng/Downloads/CarPartsDetectionChallenge-master/Data/Source_Images/Test_Images --classes /home/hmcheng/Downloads/CarPartsDetectionChallenge-master/Data/Model_Weights/data_classes.txt --output /home/hmcheng/Downloads/CarPartsDetectionChallenge-master/Data/Source_Images/Test_Image_Detection_Results --yolo_model /home/hmcheng/Downloads/CarPartsDetectionChallenge-master/Data/Model_Weights/trained_weights_final.h5 --box_file /home/hmcheng/Downloads/CarPartsDetectionChallenge-master/Data/Source_Images/Test_Image_Detection_Results/Detection_Results.csv --anchors /home/hmcheng/Downloads/CarPartsDetectionChallenge-master/2_Training/src/keras_yolo3/model_data/yolo_anchors.txt --file_types .jpg .jpeg .png  

Traceback (most recent call last):
  File "/home/hmcheng/Downloads/CarPartsDetectionChallenge-master/3_Inference/Detector.py", line 21, in <module>
    from keras_yolo3.yolo import YOLO, detect_video
ImportError: No module named keras_yolo3.yolo
Detected Cat Faces in 0.0 seconds

**Comment by bhadreshpsavani** [comment]
Hi @vincentcheng62,
Thanks for letting me know.
Do you know the cause of the issue?

**Comment by bhadreshpsavani** [comment]
Hi @vincentcheng62 
I have fixed the issue,
Let me know if it still persists
